/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.neu.csye6200.peoplemanagementsystem.frames;

import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author Nata
 */
public class AdminHomeJPanel extends JPanel {

    /**
     * Creates new form HomeJPanel
     */
    
    JPanel mainWorkArea;
    
    public AdminHomeJPanel(JPanel mainWorkArea) {
        initComponents();
        this.mainWorkArea = mainWorkArea;
        
//        setHomepage();
    }
    
//    private void setHomepage() {
//       HomeScreen hs = new HomeScreen(workArea,sys,this);
//       workArea.add("HomeScreen",hs);
//       CardLayout layout = (CardLayout) workArea.getLayout();
//       layout.next(workArea);
//    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_HomeTitle = new javax.swing.JLabel();
        btn_EmployeeSearch = new javax.swing.JButton();
        btn_TeamSearch = new javax.swing.JButton();
        btn_EmployeeTermination = new javax.swing.JButton();
        btn_CreateTeam = new javax.swing.JButton();
        btn_EmployeeList = new javax.swing.JButton();
        btn_TeamList = new javax.swing.JButton();
        btn_TeamTermination = new javax.swing.JButton();
        btn_Logout = new javax.swing.JButton();

        lbl_HomeTitle.setText("HOME");

        btn_EmployeeSearch.setText("Employee Search");
        btn_EmployeeSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_EmployeeSearchActionPerformed(evt);
            }
        });

        btn_TeamSearch.setText("Team Search");
        btn_TeamSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_TeamSearchActionPerformed(evt);
            }
        });

        btn_EmployeeTermination.setText("Employee Termination");
        btn_EmployeeTermination.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_EmployeeTerminationActionPerformed(evt);
            }
        });

        btn_CreateTeam.setText("Create Team");
        btn_CreateTeam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CreateTeamActionPerformed(evt);
            }
        });

        btn_EmployeeList.setText("Employee List");
        btn_EmployeeList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_EmployeeListActionPerformed(evt);
            }
        });

        btn_TeamList.setText("Team List");
        btn_TeamList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_TeamListActionPerformed(evt);
            }
        });

        btn_TeamTermination.setText("Team Termination");
        btn_TeamTermination.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_TeamTerminationActionPerformed(evt);
            }
        });

        btn_Logout.setText("LOGOUT");
        btn_Logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_LogoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(148, 148, 148)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_EmployeeTermination)
                    .addComponent(btn_EmployeeSearch)
                    .addComponent(btn_TeamSearch)
                    .addComponent(btn_CreateTeam)
                    .addComponent(btn_EmployeeList)
                    .addComponent(btn_TeamList)
                    .addComponent(btn_TeamTermination))
                .addContainerGap(131, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(170, 170, 170)
                .addComponent(lbl_HomeTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_Logout)
                .addGap(23, 23, 23))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_HomeTitle)
                    .addComponent(btn_Logout))
                .addGap(32, 32, 32)
                .addComponent(btn_EmployeeSearch)
                .addGap(18, 18, 18)
                .addComponent(btn_EmployeeList)
                .addGap(18, 18, 18)
                .addComponent(btn_TeamSearch)
                .addGap(18, 18, 18)
                .addComponent(btn_TeamList)
                .addGap(18, 18, 18)
                .addComponent(btn_CreateTeam)
                .addGap(18, 18, 18)
                .addComponent(btn_EmployeeTermination)
                .addGap(18, 18, 18)
                .addComponent(btn_TeamTermination)
                .addContainerGap(35, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btn_EmployeeSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_EmployeeSearchActionPerformed
        // TODO add your handling code here:
            JPanel selectedPanel = new EmployeeSearchJPanel(mainWorkArea);
            mainWorkArea.add("WorkAreaJPanel", selectedPanel);
            CardLayout layout = (CardLayout) mainWorkArea.getLayout();
            layout.next(mainWorkArea);
    }//GEN-LAST:event_btn_EmployeeSearchActionPerformed
 
    private void btn_TeamSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_TeamSearchActionPerformed
        // TODO add your handling code here:
            JPanel selectedPanel = new TeamSearchJPanel(mainWorkArea);
            mainWorkArea.add("WorkAreaJPanel", selectedPanel);
            CardLayout layout = (CardLayout) mainWorkArea.getLayout();
            layout.next(mainWorkArea);
    }//GEN-LAST:event_btn_TeamSearchActionPerformed
  
    private void btn_EmployeeTerminationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_EmployeeTerminationActionPerformed
        // TODO add your handling code here:
            JPanel selectedPanel = new TerminateEmployeeJPanel(mainWorkArea);
            mainWorkArea.add("WorkAreaJPanel", selectedPanel);
            CardLayout layout = (CardLayout) mainWorkArea.getLayout();
            layout.next(mainWorkArea);
    }//GEN-LAST:event_btn_EmployeeTerminationActionPerformed

    private void btn_EmployeeListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_EmployeeListActionPerformed
        // TODO add your handling code here:
            JPanel selectedPanel = new EmployeeListJPanel(mainWorkArea);
            mainWorkArea.add("WorkAreaJPanel", selectedPanel);
            CardLayout layout = (CardLayout) mainWorkArea.getLayout();
            layout.next(mainWorkArea);
    }//GEN-LAST:event_btn_EmployeeListActionPerformed

    private void btn_TeamListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_TeamListActionPerformed
        // TODO add your handling code here:
            JPanel selectedPanel = new TeamListJPanel(mainWorkArea);
            mainWorkArea.add("WorkAreaJPanel", selectedPanel);
            CardLayout layout = (CardLayout) mainWorkArea.getLayout();
            layout.next(mainWorkArea);
    }//GEN-LAST:event_btn_TeamListActionPerformed

    private void btn_TeamTerminationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_TeamTerminationActionPerformed
        // TODO add your handling code here:
            JPanel selectedPanel = new TerminateTeamJPanel(mainWorkArea);
            mainWorkArea.add("WorkAreaJPanel", selectedPanel);
            CardLayout layout = (CardLayout) mainWorkArea.getLayout();
            layout.next(mainWorkArea);
    }//GEN-LAST:event_btn_TeamTerminationActionPerformed

    private void btn_CreateTeamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CreateTeamActionPerformed
        // TODO add your handling code here:
            JPanel selectedPanel = new TeamCreateJPanel(mainWorkArea);
            mainWorkArea.add("WorkAreaJPanel", selectedPanel);
            CardLayout layout = (CardLayout) mainWorkArea.getLayout();
            layout.next(mainWorkArea);
    }//GEN-LAST:event_btn_CreateTeamActionPerformed

    private void btn_LogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_LogoutActionPerformed
        // TODO add your handling code here:
        JPanel selectedPanel = new LoginJPanel(mainWorkArea);
        mainWorkArea.add("WorkAreaJPanel", selectedPanel);
        CardLayout layout = (CardLayout) mainWorkArea.getLayout();
        layout.next(mainWorkArea);
    }//GEN-LAST:event_btn_LogoutActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_CreateTeam;
    private javax.swing.JButton btn_EmployeeList;
    private javax.swing.JButton btn_EmployeeSearch;
    private javax.swing.JButton btn_EmployeeTermination;
    private javax.swing.JButton btn_Logout;
    private javax.swing.JButton btn_TeamList;
    private javax.swing.JButton btn_TeamSearch;
    private javax.swing.JButton btn_TeamTermination;
    private javax.swing.JLabel lbl_HomeTitle;
    // End of variables declaration//GEN-END:variables
}
