/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.neu.csye6200.peoplemanagementsystem.frames;

import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author Nata
 */
public class EmployeeHomeJPanel extends JPanel {

    /**
     * Creates new form EmployeeHomeJPanel
     */
    
    JPanel mainWorkArea;
    
    public EmployeeHomeJPanel(JPanel mainWorkArea) {
        initComponents();
        this.mainWorkArea = mainWorkArea;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_HomeTitle = new javax.swing.JLabel();
        btn_PersonalInformation = new javax.swing.JButton();
        btn_Logout = new javax.swing.JButton();

        lbl_HomeTitle.setText("HOME");

        btn_PersonalInformation.setText("Personal Information");
        btn_PersonalInformation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_PersonalInformationActionPerformed(evt);
            }
        });

        btn_Logout.setText("LOGOUT");
        btn_Logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_LogoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(148, 148, 148)
                .addComponent(btn_PersonalInformation)
                .addContainerGap(166, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(170, 170, 170)
                .addComponent(lbl_HomeTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_Logout)
                .addGap(23, 23, 23))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_HomeTitle)
                    .addComponent(btn_Logout))
                .addGap(32, 32, 32)
                .addComponent(btn_PersonalInformation)
                .addContainerGap(327, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btn_PersonalInformationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_PersonalInformationActionPerformed
        // TODO add your handling code here:
        JPanel selectedPanel = new EmployeeInfoJPanel(mainWorkArea);
        mainWorkArea.add("WorkAreaJPanel", selectedPanel);
        CardLayout layout = (CardLayout) mainWorkArea.getLayout();
        layout.next(mainWorkArea);
    }//GEN-LAST:event_btn_PersonalInformationActionPerformed

    private void btn_LogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_LogoutActionPerformed
        // TODO add your handling code here:
        JPanel selectedPanel = new LoginJPanel(mainWorkArea);
        mainWorkArea.add("WorkAreaJPanel", selectedPanel);
        CardLayout layout = (CardLayout) mainWorkArea.getLayout();
        layout.next(mainWorkArea);
    }//GEN-LAST:event_btn_LogoutActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Logout;
    private javax.swing.JButton btn_PersonalInformation;
    private javax.swing.JLabel lbl_HomeTitle;
    // End of variables declaration//GEN-END:variables
}
