/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.neu.csye6200.peoplemanagementsystem.frames;


import edu.neu.csye6200.peoplemanagementsystem.Factory.personFactories.EmployeeBuilderFactory;
import edu.neu.csye6200.peoplemanagementsystem.builder.EmployeeBuilder;
import edu.neu.csye6200.peoplemanagementsystem.dao.EmployeeDao;
import edu.neu.csye6200.peoplemanagementsystem.pojo.Compensation;
import edu.neu.csye6200.peoplemanagementsystem.pojo.Employee;
import edu.neu.csye6200.peoplemanagementsystem.pojo.EmployeeCategory;
import edu.neu.csye6200.peoplemanagementsystem.pojo.Gender;
import edu.neu.csye6200.peoplemanagementsystem.services.SearchService;

import javax.swing.*;
import java.awt.*;
import java.time.LocalDateTime;

/**
 *
 * @author Nata
 */
public class EmployeeInfoJPanel extends JPanel {

    /**
     * Creates new form EmployeeInfoJPanel
     */
    
    JPanel mainWorkArea;
    
    public EmployeeInfoJPanel(JPanel mainWorkArea) {
        initComponents();
        this.mainWorkArea = mainWorkArea;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_UserName = new javax.swing.JLabel();
        lbl_City = new javax.swing.JLabel();
        lbl_Gender = new javax.swing.JLabel();
        txt_City = new javax.swing.JTextField();
        lbl_Password = new javax.swing.JLabel();
        txt_StreetAddress = new javax.swing.JTextField();
        lbl_IDType = new javax.swing.JLabel();
        txt_Phone = new javax.swing.JTextField();
        dd_Gender = new javax.swing.JComboBox<>();
        txt_Zipcode = new javax.swing.JTextField();
        lbl_RegisterTitle = new javax.swing.JLabel();
        lbl_Zipcode = new javax.swing.JLabel();
        txt_FirstName = new javax.swing.JTextField();
        txt_UserName = new javax.swing.JTextField();
        txt_Email = new javax.swing.JTextField();
        lbl_Phone = new javax.swing.JLabel();
        txt_LastName = new javax.swing.JTextField();
        lbl_LastName = new javax.swing.JLabel();
        lbl_Email = new javax.swing.JLabel();
        lbl_StreetAddress = new javax.swing.JLabel();
        pwf_Password = new javax.swing.JPasswordField();
        lbl_FirstName = new javax.swing.JLabel();
        txt_IDType = new javax.swing.JTextField();
        lbl_EmployeeID = new javax.swing.JLabel();
        txt_EmployeeID = new javax.swing.JTextField();
        btn_EmployeeSearch = new javax.swing.JButton();
        lbl_DateofJoining = new javax.swing.JLabel();
        txt_DateOfJoining = new javax.swing.JTextField();
        lbl_FirstName2 = new javax.swing.JLabel();
        txt_SalaryType = new javax.swing.JTextField();
        lbl_EmployeeLevel = new javax.swing.JLabel();
        txt_EmployeeLevel = new javax.swing.JTextField();
        lbl_WorkingType = new javax.swing.JLabel();
        txt_WorkingType = new javax.swing.JTextField();
        lbl_Organization = new javax.swing.JLabel();
        txt_Organization = new javax.swing.JTextField();
        lbl_TeamID = new javax.swing.JLabel();
        txt_TeamID = new javax.swing.JTextField();
        lbl_BasePay = new javax.swing.JLabel();
        txt_BasePay = new javax.swing.JTextField();
        lbl_Bonus = new javax.swing.JLabel();
        txt_Bonus = new javax.swing.JTextField();
        txt_401K = new javax.swing.JTextField();
        lbl_401K = new javax.swing.JLabel();
        txt_HealthInsurance = new javax.swing.JTextField();
        lbl_HealthInsurance = new javax.swing.JLabel();
        txt_TotalCompensation = new javax.swing.JTextField();
        lbl_TotalCompensation = new javax.swing.JLabel();
        btn_Home = new javax.swing.JButton();
        btn_Update = new javax.swing.JButton();

        lbl_UserName.setText("User Name");

        lbl_City.setText("City");

        lbl_Gender.setText("Gender");

        lbl_Password.setText("Password");

        lbl_IDType.setText("ID Type");

        dd_Gender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female", "Trans" }));

        lbl_RegisterTitle.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        lbl_RegisterTitle.setText("Personal Information");

        lbl_Zipcode.setText("Zipcode");

        txt_FirstName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_FirstNameActionPerformed(evt);
            }
        });

        lbl_Phone.setText("Phone");

        txt_LastName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_LastNameActionPerformed(evt);
            }
        });

        lbl_LastName.setText("Last Name");

        lbl_Email.setText("Email");

        lbl_StreetAddress.setText("Street Address");

        lbl_FirstName.setText("First Name");

        lbl_EmployeeID.setText("Employee ID");

        txt_EmployeeID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_EmployeeIDActionPerformed(evt);
            }
        });

        btn_EmployeeSearch.setText("Search");
        btn_EmployeeSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_EmployeeSearchActionPerformed(evt);
            }
        });

        lbl_DateofJoining.setText("Date of Joining");

        txt_DateOfJoining.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_DateOfJoiningActionPerformed(evt);
            }
        });

        lbl_FirstName2.setText("Salary Type");

        txt_SalaryType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_SalaryTypeActionPerformed(evt);
            }
        });

        lbl_EmployeeLevel.setText("Employee Level");

        txt_EmployeeLevel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_EmployeeLevelActionPerformed(evt);
            }
        });

        lbl_WorkingType.setText("Working Type");

        txt_WorkingType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_WorkingTypeActionPerformed(evt);
            }
        });

        lbl_Organization.setText("Organization");

        txt_Organization.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_OrganizationActionPerformed(evt);
            }
        });

        lbl_TeamID.setText("Team ID");

        txt_TeamID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_TeamIDActionPerformed(evt);
            }
        });

        lbl_BasePay.setText("Base Pay");

        txt_BasePay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_BasePayActionPerformed(evt);
            }
        });

        lbl_Bonus.setText("Bonus");

        txt_Bonus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_BonusActionPerformed(evt);
            }
        });

        txt_401K.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_401KActionPerformed(evt);
            }
        });

        lbl_401K.setText("401K");

        txt_HealthInsurance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_HealthInsuranceActionPerformed(evt);
            }
        });

        lbl_HealthInsurance.setText("Health Insurance");

        txt_TotalCompensation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_TotalCompensationActionPerformed(evt);
            }
        });

        lbl_TotalCompensation.setText("Total Compensation");

        btn_Home.setText("Home");
        btn_Home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_HomeActionPerformed(evt);
            }
        });

        btn_Update.setText("UPDATE");
        btn_Update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_UpdateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addComponent(lbl_EmployeeID)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addComponent(txt_EmployeeID, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_EmployeeSearch)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbl_TotalCompensation, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_TotalCompensation, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbl_401K, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(51, 51, 51)
                        .addComponent(txt_401K, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbl_Bonus, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(51, 51, 51)
                        .addComponent(txt_Bonus, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbl_BasePay, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(51, 51, 51)
                        .addComponent(txt_BasePay, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbl_TeamID, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(51, 51, 51)
                        .addComponent(txt_TeamID, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbl_FirstName2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(51, 51, 51)
                        .addComponent(txt_SalaryType, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbl_DateofJoining)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txt_DateOfJoining, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lbl_WorkingType)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbl_Organization)
                                .addGap(9, 9, 9)))
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_WorkingType, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_Organization, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lbl_EmployeeLevel, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_HealthInsurance))
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_HealthInsurance, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_EmployeeLevel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_UserName)
                            .addComponent(lbl_Password))
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(pwf_Password)
                            .addComponent(txt_UserName, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(35, 35, 35))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbl_RegisterTitle)
                .addGap(208, 208, 208)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_Update)
                    .addComponent(btn_Home))
                .addGap(84, 84, 84))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(101, 101, 101)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lbl_FirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lbl_LastName))
                            .addGap(51, 51, 51)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txt_LastName, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txt_FirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lbl_Gender)
                                .addComponent(lbl_Phone)
                                .addComponent(lbl_Email)
                                .addComponent(lbl_City)
                                .addComponent(lbl_StreetAddress)
                                .addComponent(lbl_Zipcode)
                                .addComponent(lbl_IDType))
                            .addGap(40, 40, 40)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txt_IDType, javax.swing.GroupLayout.DEFAULT_SIZE, 286, Short.MAX_VALUE)
                                .addComponent(txt_Zipcode, javax.swing.GroupLayout.DEFAULT_SIZE, 286, Short.MAX_VALUE)
                                .addComponent(txt_StreetAddress, javax.swing.GroupLayout.DEFAULT_SIZE, 286, Short.MAX_VALUE)
                                .addComponent(txt_City, javax.swing.GroupLayout.DEFAULT_SIZE, 286, Short.MAX_VALUE)
                                .addComponent(txt_Email, javax.swing.GroupLayout.DEFAULT_SIZE, 286, Short.MAX_VALUE)
                                .addComponent(txt_Phone, javax.swing.GroupLayout.DEFAULT_SIZE, 286, Short.MAX_VALUE)
                                .addComponent(dd_Gender, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addContainerGap(503, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_Home)
                    .addComponent(lbl_RegisterTitle))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_Update)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lbl_EmployeeID)
                        .addComponent(txt_EmployeeID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn_EmployeeSearch))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_UserName)
                            .addComponent(txt_UserName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_Password)
                            .addComponent(pwf_Password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_DateofJoining)
                            .addComponent(txt_DateOfJoining, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_FirstName2)
                            .addComponent(txt_SalaryType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_EmployeeLevel)
                            .addComponent(txt_EmployeeLevel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_WorkingType)
                            .addComponent(txt_WorkingType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_Organization)
                            .addComponent(txt_Organization, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_TeamID)
                            .addComponent(txt_TeamID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_BasePay)
                            .addComponent(txt_BasePay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_Bonus)
                            .addComponent(txt_Bonus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_401K)
                            .addComponent(txt_401K, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_HealthInsurance)
                            .addComponent(txt_HealthInsurance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_TotalCompensation)
                            .addComponent(txt_TotalCompensation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(38, 38, 38))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(126, 126, 126)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lbl_FirstName)
                        .addComponent(txt_FirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lbl_LastName)
                        .addComponent(txt_LastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lbl_Gender)
                        .addComponent(dd_Gender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lbl_Phone)
                        .addComponent(txt_Phone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lbl_Email)
                        .addComponent(txt_Email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(46, 46, 46)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lbl_City)
                        .addComponent(txt_City, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lbl_StreetAddress)
                        .addComponent(txt_StreetAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lbl_Zipcode)
                        .addComponent(txt_Zipcode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lbl_IDType)
                        .addComponent(txt_IDType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(52, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txt_FirstNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_FirstNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_FirstNameActionPerformed

    private void txt_LastNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_LastNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_LastNameActionPerformed

    private void txt_EmployeeIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_EmployeeIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_EmployeeIDActionPerformed

    private void btn_EmployeeSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_EmployeeSearchActionPerformed
        // TODO add your handling code here:
        
        String empID = txt_EmployeeID.getText();
        
        SearchService ss = new SearchService();
        
        Employee employee = ss.searchEmployeeBasedOnId(Integer.parseInt(empID));
        
        txt_FirstName.setText(employee.getFName());
        txt_LastName.setText(employee.getLName());
        dd_Gender.setName(employee.getGender().toString());
        txt_Phone.setText(employee.getPhone());
        txt_Email.setText(employee.getEmail());
        txt_City.setText(employee.getCity());
        txt_StreetAddress.setText(employee.getStreetAddress());
        txt_Zipcode.setText(employee.getZipCode());
        txt_IDType.setText(employee.getIdType());
        txt_UserName.setText(employee.getUserName());
        pwf_Password.setText(employee.getPassword());
        txt_DateOfJoining.setText(employee.getDateOfJoining().toString());
        txt_SalaryType.setText(employee.getEmpCategory().getSalaryType());
        txt_EmployeeLevel.setText(employee.getEmpCategory().getLevel());
        txt_WorkingType.setText(employee.getEmpCategory().getWorkingType());
        txt_Organization.setText(employee.getOrganization());
        txt_TeamID.setText(employee.getTeamId());
        txt_BasePay.setText(String.valueOf(employee.getCompensation().getBasePay()));
        txt_Bonus.setText(String.valueOf(employee.getCompensation().getBonus()));
        txt_401K.setText(String.valueOf(employee.getCompensation().getContribute401k()));
        txt_HealthInsurance.setText(String.valueOf(employee.getCompensation().getHealthinsurance()));
        txt_TotalCompensation.setText(String.valueOf(employee.getCompensation().getTotalComp()));
        
       
        
    }//GEN-LAST:event_btn_EmployeeSearchActionPerformed

    private void txt_DateOfJoiningActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_DateOfJoiningActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_DateOfJoiningActionPerformed

    private void txt_SalaryTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_SalaryTypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_SalaryTypeActionPerformed

    private void txt_EmployeeLevelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_EmployeeLevelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_EmployeeLevelActionPerformed

    private void txt_WorkingTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_WorkingTypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_WorkingTypeActionPerformed

    private void txt_OrganizationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_OrganizationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_OrganizationActionPerformed

    private void txt_TeamIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_TeamIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_TeamIDActionPerformed

    private void txt_BasePayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_BasePayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_BasePayActionPerformed

    private void txt_BonusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_BonusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_BonusActionPerformed

    private void txt_401KActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_401KActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_401KActionPerformed

    private void txt_HealthInsuranceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_HealthInsuranceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_HealthInsuranceActionPerformed

    private void txt_TotalCompensationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_TotalCompensationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_TotalCompensationActionPerformed

    private void btn_HomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_HomeActionPerformed
        // TODO add your handling code here:
        JPanel selectedPanel = new EmployeeHomeJPanel(mainWorkArea);
        mainWorkArea.add("WorkAreaJPanel", selectedPanel);
        CardLayout layout = (CardLayout) mainWorkArea.getLayout();
        layout.next(mainWorkArea);
    }//GEN-LAST:event_btn_HomeActionPerformed

    private void btn_UpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_UpdateActionPerformed
        // TODO add your handling code here:

        String empid = txt_EmployeeID.getText();

        String fname = txt_FirstName.getText();
        String lname = txt_LastName.getText();
        String gender = dd_Gender.getSelectedItem().toString();
        String phone = txt_Phone.getText();
        String email = txt_Email.getText();
        String city = txt_City.getText();
        String streetaddress = txt_StreetAddress.getText();
        String zipcode = txt_Zipcode.getText();
        String idtype = txt_IDType.getText();
        String username = txt_UserName.getText();
        String password = String.valueOf(pwf_Password.getPassword());
        
        String doj = txt_DateOfJoining.getText();
        String saltype = txt_SalaryType.getText();
        String emplvl = txt_EmployeeLevel.getText();
        String worktype = txt_WorkingType.getText();
        String org = txt_Organization.getText();
        String teamid = txt_TeamID.getText();
        Double compbase = Double.parseDouble(txt_BasePay.getText());
        Double compbonus = Double.parseDouble(txt_Bonus.getText());
        Double comp401 = Double.parseDouble(txt_401K.getText());
        Double compinsurance = Double.parseDouble(txt_HealthInsurance.getText());
        Double comptotal = Double.parseDouble(txt_TotalCompensation.getText());
        
        
        Gender genderenum;

        
        if(dd_Gender.getSelectedItem().toString() == "Male"){
            genderenum = Gender.male;
        }
        else if(dd_Gender.getSelectedItem().toString() == "Female"){
            genderenum = Gender.female;
        }
        else{
            genderenum = Gender.trans;
        }
        
        EmployeeCategory empcat = new EmployeeCategory(saltype,emplvl,worktype);
        
        Compensation compensation = new Compensation(compbase, compbonus, compinsurance, comp401, comptotal);
        
        EmployeeBuilderFactory employeeBuilderFactory = EmployeeBuilderFactory.getInstance();
        EmployeeBuilder employeeBuilder = employeeBuilderFactory.getBuilder();

        Employee employee = employeeBuilder.createEntity()
                .setEmpId(empid)
                .setFName(fname)
                .setLName(lname)
                .setGender(genderenum)
                .setPhone(phone)
                .setEmail(email)
                .setCity(city)
                .setStreetAddress(streetaddress)
                .setZipCode(zipcode)
                .setIdType(idtype)
                .setUserName(username)
                .setPassword(password)
                .setDateOfJoining(LocalDateTime.MAX)
                .setEmployeeCategory(empcat)
                .setOrganization(org)
                .setTeam(teamid)
                .setCompensation(compensation)
                .build();
        
        EmployeeDao.update(employee);
        
        JOptionPane.showMessageDialog(null, "Your information has been updated!");
        
    }//GEN-LAST:event_btn_UpdateActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_EmployeeSearch;
    private javax.swing.JButton btn_Home;
    private javax.swing.JButton btn_Update;
    private javax.swing.JComboBox<String> dd_Gender;
    private javax.swing.JLabel lbl_401K;
    private javax.swing.JLabel lbl_BasePay;
    private javax.swing.JLabel lbl_Bonus;
    private javax.swing.JLabel lbl_City;
    private javax.swing.JLabel lbl_DateofJoining;
    private javax.swing.JLabel lbl_Email;
    private javax.swing.JLabel lbl_EmployeeID;
    private javax.swing.JLabel lbl_EmployeeLevel;
    private javax.swing.JLabel lbl_FirstName;
    private javax.swing.JLabel lbl_FirstName2;
    private javax.swing.JLabel lbl_Gender;
    private javax.swing.JLabel lbl_HealthInsurance;
    private javax.swing.JLabel lbl_IDType;
    private javax.swing.JLabel lbl_LastName;
    private javax.swing.JLabel lbl_Organization;
    private javax.swing.JLabel lbl_Password;
    private javax.swing.JLabel lbl_Phone;
    private javax.swing.JLabel lbl_RegisterTitle;
    private javax.swing.JLabel lbl_StreetAddress;
    private javax.swing.JLabel lbl_TeamID;
    private javax.swing.JLabel lbl_TotalCompensation;
    private javax.swing.JLabel lbl_UserName;
    private javax.swing.JLabel lbl_WorkingType;
    private javax.swing.JLabel lbl_Zipcode;
    private javax.swing.JPasswordField pwf_Password;
    private javax.swing.JTextField txt_401K;
    private javax.swing.JTextField txt_BasePay;
    private javax.swing.JTextField txt_Bonus;
    private javax.swing.JTextField txt_City;
    private javax.swing.JTextField txt_DateOfJoining;
    private javax.swing.JTextField txt_Email;
    private javax.swing.JTextField txt_EmployeeID;
    private javax.swing.JTextField txt_EmployeeLevel;
    private javax.swing.JTextField txt_FirstName;
    private javax.swing.JTextField txt_HealthInsurance;
    private javax.swing.JTextField txt_IDType;
    private javax.swing.JTextField txt_LastName;
    private javax.swing.JTextField txt_Organization;
    private javax.swing.JTextField txt_Phone;
    private javax.swing.JTextField txt_SalaryType;
    private javax.swing.JTextField txt_StreetAddress;
    private javax.swing.JTextField txt_TeamID;
    private javax.swing.JTextField txt_TotalCompensation;
    private javax.swing.JTextField txt_UserName;
    private javax.swing.JTextField txt_WorkingType;
    private javax.swing.JTextField txt_Zipcode;
    // End of variables declaration//GEN-END:variables
}
