/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.neu.csye6200.peoplemanagementsystem.frames;

import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author Nata
 */
public class HomeJPanel extends JPanel {

    /**
     * Creates new form HomeJPanel
     */
    
    JPanel mainWorkArea;
    
    public HomeJPanel(JPanel mainWorkArea) {
        initComponents();
        this.mainWorkArea = mainWorkArea;
        
//        setHomepage();
    }
    
//    private void setHomepage() {
//       HomeScreen hs = new HomeScreen(workArea,sys,this);
//       workArea.add("HomeScreen",hs);
//       CardLayout layout = (CardLayout) workArea.getLayout();
//       layout.next(workArea);
//    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btn_EmployeeSearch = new javax.swing.JButton();
        btn_TeamSearch = new javax.swing.JButton();
        btn_EmployeeTermination = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        btn_EmployeeList = new javax.swing.JButton();
        btn_TeamList = new javax.swing.JButton();

        jLabel1.setText("HOME");

        btn_EmployeeSearch.setText("Employee Search");
        btn_EmployeeSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_EmployeeSearchActionPerformed(evt);
            }
        });

        btn_TeamSearch.setText("Team Search");
        btn_TeamSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_TeamSearchActionPerformed(evt);
            }
        });

        btn_EmployeeTermination.setText("Employee Termination");
        btn_EmployeeTermination.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_EmployeeTerminationActionPerformed(evt);
            }
        });

        jButton1.setText("Create Team");

        btn_EmployeeList.setText("Employee List");
        btn_EmployeeList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_EmployeeListActionPerformed(evt);
            }
        });

        btn_TeamList.setText("Team List");
        btn_TeamList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_TeamListActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(170, 170, 170)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(148, 148, 148)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_EmployeeTermination)
                            .addComponent(btn_EmployeeSearch)
                            .addComponent(btn_TeamSearch)
                            .addComponent(jButton1)
                            .addComponent(btn_EmployeeList)
                            .addComponent(btn_TeamList))))
                .addContainerGap(131, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(41, 41, 41)
                .addComponent(btn_EmployeeSearch)
                .addGap(18, 18, 18)
                .addComponent(btn_EmployeeList)
                .addGap(18, 18, 18)
                .addComponent(btn_TeamSearch)
                .addGap(18, 18, 18)
                .addComponent(btn_TeamList)
                .addGap(22, 22, 22)
                .addComponent(btn_EmployeeTermination)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(72, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btn_EmployeeSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_EmployeeSearchActionPerformed
        // TODO add your handling code here:
            JPanel selectedPanel = new EmployeeSearchJPanel(mainWorkArea);
            mainWorkArea.add("WorkAreaJPanel", selectedPanel);
            CardLayout layout = (CardLayout) mainWorkArea.getLayout();
            layout.next(mainWorkArea);
    }//GEN-LAST:event_btn_EmployeeSearchActionPerformed
 
    private void btn_TeamSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_TeamSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_TeamSearchActionPerformed
  
    private void btn_EmployeeTerminationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_EmployeeTerminationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_EmployeeTerminationActionPerformed

    private void btn_EmployeeListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_EmployeeListActionPerformed
        // TODO add your handling code here:
            JPanel selectedPanel = new EmployeeListJPanel(mainWorkArea);
            mainWorkArea.add("WorkAreaJPanel", selectedPanel);
            CardLayout layout = (CardLayout) mainWorkArea.getLayout();
            layout.next(mainWorkArea);
    }//GEN-LAST:event_btn_EmployeeListActionPerformed

    private void btn_TeamListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_TeamListActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_TeamListActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_EmployeeList;
    private javax.swing.JButton btn_EmployeeSearch;
    private javax.swing.JButton btn_EmployeeTermination;
    private javax.swing.JButton btn_TeamList;
    private javax.swing.JButton btn_TeamSearch;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
