/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.neu.csye6200.peoplemanagementsystem.frames;

import edu.neu.csye6200.peoplemanagementsystem.dao.EmployeeDao;
import edu.neu.csye6200.peoplemanagementsystem.pojo.Employee;
import edu.neu.csye6200.peoplemanagementsystem.services.EmployeeService;

import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Nata
 */
public class LoginJPanel extends JPanel {

    /**
     * Creates new form LoginJPanel
     */
    
    JPanel mainWorkArea;
    
    public LoginJPanel(JPanel mainWorkArea) {
        initComponents();
        this.mainWorkArea = mainWorkArea;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_LoginTitle = new javax.swing.JLabel();
        lbl_Password = new javax.swing.JLabel();
        lbl_UserName = new javax.swing.JLabel();
        txt_UserName = new javax.swing.JTextField();
        pwf_Password = new javax.swing.JPasswordField();
        btn_Login = new javax.swing.JButton();
        btn_register = new javax.swing.JButton();

        lbl_LoginTitle.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        lbl_LoginTitle.setText("LOGIN PAGE");

        lbl_Password.setText("Password:");

        lbl_UserName.setText("User Name:");

        btn_Login.setText("LOGIN");
        btn_Login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_LoginActionPerformed(evt);
            }
        });

        btn_register.setText("REGISTER");
        btn_register.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_registerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lbl_LoginTitle)
                .addGap(140, 140, 140))
            .addGroup(layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lbl_Password)
                            .addComponent(lbl_UserName))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_UserName)
                            .addComponent(pwf_Password, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(117, 117, 117)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_register)
                            .addComponent(btn_Login, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(97, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(lbl_LoginTitle)
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_UserName)
                    .addComponent(txt_UserName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_Password)
                    .addComponent(pwf_Password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btn_Login)
                .addGap(18, 18, 18)
                .addComponent(btn_register)
                .addContainerGap(57, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btn_LoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_LoginActionPerformed
        // TODO add your handling code here:
        if (txt_UserName.getText().equals("admin") && pwf_Password.getText().equals("123")) {
            JOptionPane.showMessageDialog(null, "Logged In As Admin Successful!");
            clearLoginFields();

            JPanel selectedPanel = new AdminHomeJPanel(mainWorkArea);
            mainWorkArea.add("WorkAreaJPanel", selectedPanel);
            CardLayout layout = (CardLayout) mainWorkArea.getLayout();
            layout.next(mainWorkArea);

        }
        else  {

            EmployeeService employeeService = new EmployeeService();
            String message = employeeService.signIn(txt_UserName.getText(), pwf_Password.getText());

            if ("Success".equals(message)) {
                JOptionPane.showMessageDialog(null, "Logged In As Employee Successful!");
                clearLoginFields();

                JPanel selectedPanel = new EmployeeHomeJPanel(mainWorkArea);
                mainWorkArea.add("WorkAreaJPanel", selectedPanel);
                CardLayout layout = (CardLayout) mainWorkArea.getLayout();
                layout.next(mainWorkArea);
            } else {
                JOptionPane.showMessageDialog(null, message);
                clearLoginFields();

                JPanel selectedPanel = new LoginJPanel(mainWorkArea);
                mainWorkArea.add("WorkAreaJPanel", selectedPanel);
                CardLayout layout = (CardLayout) mainWorkArea.getLayout();
                layout.next(mainWorkArea);
            }



        }
    }//GEN-LAST:event_btn_LoginActionPerformed

    private void btn_registerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_registerActionPerformed
        // TODO add your handling code here:
            JPanel selectedPanel = new RegisterJPanel(mainWorkArea);
            mainWorkArea.add("WorkAreaJPanel", selectedPanel);
            CardLayout layout = (CardLayout) mainWorkArea.getLayout();
            layout.next(mainWorkArea);
    }//GEN-LAST:event_btn_registerActionPerformed

    public void clearLoginFields() {

        txt_UserName.setText("");
        pwf_Password.setText("");

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Login;
    private javax.swing.JButton btn_register;
    private javax.swing.JLabel lbl_LoginTitle;
    private javax.swing.JLabel lbl_Password;
    private javax.swing.JLabel lbl_UserName;
    private javax.swing.JPasswordField pwf_Password;
    private javax.swing.JTextField txt_UserName;
    // End of variables declaration//GEN-END:variables
}
