/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.neu.csye6200.peoplemanagementsystem.frames;

import edu.neu.csye6200.peoplemanagementsystem.Factory.personFactories.EmployeeBuilderFactory;
import edu.neu.csye6200.peoplemanagementsystem.builder.EmployeeBuilder;
import edu.neu.csye6200.peoplemanagementsystem.dao.EmployeeDao;
import edu.neu.csye6200.peoplemanagementsystem.pojo.Employee;
import edu.neu.csye6200.peoplemanagementsystem.pojo.Gender;

import java.awt.CardLayout;
import java.time.LocalDateTime;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Nata
 */
public class RegisterJPanel extends JPanel {

    /**
     * Creates new form RegisterJPanel
     */
    
    JPanel mainWorkArea;
    
    public RegisterJPanel(JPanel mainWorkArea) {
        initComponents();
        this.mainWorkArea = mainWorkArea;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_RegisterTitle = new javax.swing.JLabel();
        lbl_FirstName = new javax.swing.JLabel();
        lbl_LastName = new javax.swing.JLabel();
        lbl_Gender = new javax.swing.JLabel();
        lbl_Phone = new javax.swing.JLabel();
        txt_FirstName = new javax.swing.JTextField();
        lbl_Email = new javax.swing.JLabel();
        lbl_City = new javax.swing.JLabel();
        lbl_StreetAddress = new javax.swing.JLabel();
        lbl_Zipcode = new javax.swing.JLabel();
        lbl_IDType = new javax.swing.JLabel();
        txt_LastName = new javax.swing.JTextField();
        txt_Phone = new javax.swing.JTextField();
        txt_Email = new javax.swing.JTextField();
        txt_City = new javax.swing.JTextField();
        txt_StreetAddress = new javax.swing.JTextField();
        txt_Zipcode = new javax.swing.JTextField();
        txt_IDType = new javax.swing.JTextField();
        btn_Register = new javax.swing.JButton();
        dd_Gender = new javax.swing.JComboBox<>();
        lbl_UserName = new javax.swing.JLabel();
        txt_UserName = new javax.swing.JTextField();
        lbl_Password = new javax.swing.JLabel();
        pwf_Password = new javax.swing.JPasswordField();
        btn_Login = new javax.swing.JButton();

        lbl_RegisterTitle.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        lbl_RegisterTitle.setText("REGISTER");

        lbl_FirstName.setText("First Name");

        lbl_LastName.setText("Last Name");

        lbl_Gender.setText("Gender");

        lbl_Phone.setText("Phone");

        txt_FirstName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_FirstNameActionPerformed(evt);
            }
        });

        lbl_Email.setText("Email");

        lbl_City.setText("City");

        lbl_StreetAddress.setText("Street Address");

        lbl_Zipcode.setText("Zipcode");

        lbl_IDType.setText("ID Type");

        txt_LastName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_LastNameActionPerformed(evt);
            }
        });

        btn_Register.setText("REGISTER");
        btn_Register.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_RegisterActionPerformed(evt);
            }
        });

        dd_Gender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female", "Trans" }));

        lbl_UserName.setText("User Name");

        lbl_Password.setText("Password");

        btn_Login.setText("LOGIN");
        btn_Login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_LoginActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(307, 307, 307)
                        .addComponent(lbl_RegisterTitle))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(136, 136, 136)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbl_FirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbl_LastName))
                                .addGap(51, 51, 51)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_LastName, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_FirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbl_Gender)
                                    .addComponent(lbl_Phone)
                                    .addComponent(lbl_Email))
                                .addGap(79, 79, 79)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txt_Email, javax.swing.GroupLayout.DEFAULT_SIZE, 286, Short.MAX_VALUE)
                                    .addComponent(txt_Phone, javax.swing.GroupLayout.DEFAULT_SIZE, 286, Short.MAX_VALUE)
                                    .addComponent(dd_Gender, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbl_City)
                                    .addComponent(lbl_StreetAddress)
                                    .addComponent(lbl_Zipcode)
                                    .addComponent(lbl_IDType)
                                    .addComponent(lbl_UserName)
                                    .addComponent(lbl_Password))
                                .addGap(40, 40, 40)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txt_UserName)
                                    .addComponent(txt_IDType, javax.swing.GroupLayout.DEFAULT_SIZE, 286, Short.MAX_VALUE)
                                    .addComponent(txt_Zipcode, javax.swing.GroupLayout.DEFAULT_SIZE, 286, Short.MAX_VALUE)
                                    .addComponent(txt_StreetAddress, javax.swing.GroupLayout.DEFAULT_SIZE, 286, Short.MAX_VALUE)
                                    .addComponent(txt_City, javax.swing.GroupLayout.DEFAULT_SIZE, 286, Short.MAX_VALUE)
                                    .addComponent(pwf_Password)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(156, 156, 156)
                                .addComponent(btn_Register))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(168, 168, 168)
                                .addComponent(btn_Login)))))
                .addContainerGap(148, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_RegisterTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_FirstName)
                    .addComponent(txt_FirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_LastName)
                    .addComponent(txt_LastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_Gender)
                    .addComponent(dd_Gender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_Phone)
                    .addComponent(txt_Phone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_Email)
                    .addComponent(txt_Email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_City)
                    .addComponent(txt_City, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_StreetAddress)
                    .addComponent(txt_StreetAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_Zipcode)
                    .addComponent(txt_Zipcode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_IDType)
                    .addComponent(txt_IDType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_UserName)
                    .addComponent(txt_UserName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_Password)
                    .addComponent(pwf_Password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                .addComponent(btn_Register)
                .addGap(18, 18, 18)
                .addComponent(btn_Login)
                .addGap(88, 88, 88))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txt_LastNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_LastNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_LastNameActionPerformed

    private void btn_RegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_RegisterActionPerformed
        // TODO add your handling code here:
        
        String fname = txt_FirstName.getText();
        String lname = txt_LastName.getText();
        String gender = dd_Gender.getSelectedItem().toString();
        String phone = txt_Phone.getText();
        String email = txt_Email.getText();
        String city = txt_City.getText();
        String streetaddress = txt_StreetAddress.getText();
        String zipcode = txt_Zipcode.getText();
        String idtype = txt_IDType.getText();
        String username = txt_UserName.getText();
        String password = String.valueOf(pwf_Password.getPassword());
        
        Gender genderenum;

        
        if(dd_Gender.getSelectedItem().toString() == "Male"){
            genderenum = Gender.male;
        }
        else if(dd_Gender.getSelectedItem().toString() == "Female"){
            genderenum = Gender.female;
        }
        else{
            genderenum = Gender.trans;
        }
        
        EmployeeBuilderFactory employeeBuilderFactory = EmployeeBuilderFactory.getInstance();
        EmployeeBuilder employeeBuilder = employeeBuilderFactory.getBuilder();

        Employee employee = employeeBuilder.createEntity()
                .setFName(fname)
                .setLName(lname)
                .setGender(genderenum)
                .setPhone(phone)
                .setEmail(email)
                .setCity(city)
                .setStreetAddress(streetaddress)
                .setZipCode(zipcode)
                .setIdType(idtype)
                .setUserName(username)
                .setPassword(password)
                .build();
        
        EmployeeDao.save(employee);
        
        JOptionPane.showMessageDialog(null, "You have been registerd!\nYou will now be redirected to the login page!");
        
       LoginJPanel ls = new LoginJPanel(mainWorkArea);
       mainWorkArea.add("LoginScreen",ls);
       CardLayout layout = (CardLayout) mainWorkArea.getLayout();
       layout.next(mainWorkArea);
    }//GEN-LAST:event_btn_RegisterActionPerformed

    private void txt_FirstNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_FirstNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_FirstNameActionPerformed

    private void btn_LoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_LoginActionPerformed
        // TODO add your handling code here:
        JPanel selectedPanel = new LoginJPanel(mainWorkArea);
        mainWorkArea.add("WorkAreaJPanel", selectedPanel);
        CardLayout layout = (CardLayout) mainWorkArea.getLayout();
        layout.next(mainWorkArea);
    }//GEN-LAST:event_btn_LoginActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Login;
    private javax.swing.JButton btn_Register;
    private javax.swing.JComboBox<String> dd_Gender;
    private javax.swing.JLabel lbl_City;
    private javax.swing.JLabel lbl_Email;
    private javax.swing.JLabel lbl_FirstName;
    private javax.swing.JLabel lbl_Gender;
    private javax.swing.JLabel lbl_IDType;
    private javax.swing.JLabel lbl_LastName;
    private javax.swing.JLabel lbl_Password;
    private javax.swing.JLabel lbl_Phone;
    private javax.swing.JLabel lbl_RegisterTitle;
    private javax.swing.JLabel lbl_StreetAddress;
    private javax.swing.JLabel lbl_UserName;
    private javax.swing.JLabel lbl_Zipcode;
    private javax.swing.JPasswordField pwf_Password;
    private javax.swing.JTextField txt_City;
    private javax.swing.JTextField txt_Email;
    private javax.swing.JTextField txt_FirstName;
    private javax.swing.JTextField txt_IDType;
    private javax.swing.JTextField txt_LastName;
    private javax.swing.JTextField txt_Phone;
    private javax.swing.JTextField txt_StreetAddress;
    private javax.swing.JTextField txt_UserName;
    private javax.swing.JTextField txt_Zipcode;
    // End of variables declaration//GEN-END:variables
}
