/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.neu.csye6200.peoplemanagementsystem.frames;

import edu.neu.csye6200.peoplemanagementsystem.dao.TeamDao;
import edu.neu.csye6200.peoplemanagementsystem.pojo.TeamObject;

import java.awt.CardLayout;
import javax.swing.*;

/**
 *
 * @author Nata
 */
public class TeamCreateJPanel extends JPanel {

    /**
     * Creates new form TeamCreateJPanel
     */
    
    JPanel mainWorkArea;
    
    public TeamCreateJPanel(JPanel mainWorkArea) {
        initComponents();
        this.mainWorkArea = mainWorkArea;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_TeamCreateTitle = new javax.swing.JLabel();
        txt_TeamName = new javax.swing.JTextField();
        txt_TeamType = new javax.swing.JTextField();
        btn_CreateTeam = new javax.swing.JButton();
        btn_Home = new javax.swing.JButton();
        lbl_TeamName = new javax.swing.JLabel();
        lbl_TeamType = new javax.swing.JLabel();

        lbl_TeamCreateTitle.setText("TEAM CREATE");

        btn_CreateTeam.setText("CREATE TEAM");
        btn_CreateTeam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CreateTeamActionPerformed(evt);
            }
        });

        btn_Home.setText("Home");
        btn_Home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_HomeActionPerformed(evt);
            }
        });

        lbl_TeamName.setText("Team Name");

        lbl_TeamType.setText("Team Type");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lbl_TeamName)
                            .addComponent(lbl_TeamType))
                        .addGap(55, 55, 55)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_TeamName, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_TeamType, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(193, 193, 193)
                        .addComponent(btn_CreateTeam)))
                .addContainerGap(201, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(171, 171, 171)
                .addComponent(lbl_TeamCreateTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_Home)
                .addGap(100, 100, 100))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_TeamCreateTitle)
                    .addComponent(btn_Home))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_TeamName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_TeamName))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_TeamType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_TeamType))
                .addGap(34, 34, 34)
                .addComponent(btn_CreateTeam)
                .addContainerGap(240, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btn_CreateTeamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CreateTeamActionPerformed
        // TODO add your handling code here:
        String tname = txt_TeamName.getText();
        String ttype = txt_TeamType.getText();
        
        TeamObject tobj = new TeamObject();
        tobj.setTeamName(tname);
        tobj.setTeamType(ttype);
        TeamDao.save(tobj);

        JOptionPane.showMessageDialog(null, "Team has been created!");
        
    }//GEN-LAST:event_btn_CreateTeamActionPerformed

    private void btn_HomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_HomeActionPerformed
        // TODO add your handling code here:
        JPanel selectedPanel = new AdminHomeJPanel(mainWorkArea);
        mainWorkArea.add("WorkAreaJPanel", selectedPanel);
        CardLayout layout = (CardLayout) mainWorkArea.getLayout();
        layout.next(mainWorkArea);
    }//GEN-LAST:event_btn_HomeActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_CreateTeam;
    private javax.swing.JButton btn_Home;
    private javax.swing.JLabel lbl_TeamCreateTitle;
    private javax.swing.JLabel lbl_TeamName;
    private javax.swing.JLabel lbl_TeamType;
    private javax.swing.JTextField txt_TeamName;
    private javax.swing.JTextField txt_TeamType;
    // End of variables declaration//GEN-END:variables
}
