/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.neu.csye6200.peoplemanagementsystem.frames;


import edu.neu.csye6200.peoplemanagementsystem.pojo.TeamObject;
import edu.neu.csye6200.peoplemanagementsystem.services.SearchService;

import java.awt.CardLayout;
import java.util.List;
import javax.swing.JPanel;

/**
 *
 * @author Nata
 */
public class TeamSearchJPanel extends JPanel {

    /**
     * Creates new form TeamSearchJPanel
     */
    
    JPanel mainWorkArea;
    
    public TeamSearchJPanel(JPanel mainWorkArea) {
        initComponents();
        this.mainWorkArea = mainWorkArea;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_TeamSearchTitle = new javax.swing.JLabel();
        txt_SearchField = new javax.swing.JTextField();
        cmb_SearchType = new javax.swing.JComboBox<>();
        btn_SearchTeam = new javax.swing.JButton();
        btn_Home = new javax.swing.JButton();
        cmb_SortType = new javax.swing.JComboBox<>();

        lbl_TeamSearchTitle.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        lbl_TeamSearchTitle.setText("Team Search");

        txt_SearchField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_SearchFieldActionPerformed(evt);
            }
        });

        cmb_SearchType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Name", "Type" }));
        cmb_SearchType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_SearchTypeActionPerformed(evt);
            }
        });

        btn_SearchTeam.setText("SEARCH");
        btn_SearchTeam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SearchTeamActionPerformed(evt);
            }
        });

        btn_Home.setText("Home");
        btn_Home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_HomeActionPerformed(evt);
            }
        });

        cmb_SortType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "No Sort", "Member Count" }));
        cmb_SortType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_SortTypeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addComponent(txt_SearchField, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cmb_SearchType, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cmb_SortType, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(269, 269, 269)
                        .addComponent(btn_SearchTeam, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(27, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(257, 257, 257)
                .addComponent(lbl_TeamSearchTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_Home)
                .addGap(30, 30, 30))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_TeamSearchTitle)
                    .addComponent(btn_Home))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_SearchField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmb_SearchType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmb_SortType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addComponent(btn_SearchTeam)
                .addContainerGap(206, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txt_SearchFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_SearchFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_SearchFieldActionPerformed

    private void cmb_SearchTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_SearchTypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmb_SearchTypeActionPerformed

    private void btn_SearchTeamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SearchTeamActionPerformed
        // TODO add your handling code here:
        
        String txt = txt_SearchField.getText();
        String type = cmb_SearchType.getSelectedItem().toString().toLowerCase();
        String sort = null;
        
        SearchService ss = new SearchService();
  
        
        if(cmb_SortType.getSelectedItem().toString() == "Member Count"){
            sort = "Member Count";
        }
        
        
        List<TeamObject> teamlist = ss.searchAndSortTeam(type, txt, sort);
        
        JPanel selectedPanel = new TeamListJPanel(mainWorkArea,teamlist);
        mainWorkArea.add("WorkAreaJPanel", selectedPanel);
        CardLayout layout = (CardLayout) mainWorkArea.getLayout();
        layout.next(mainWorkArea);
        
    }//GEN-LAST:event_btn_SearchTeamActionPerformed

    private void btn_HomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_HomeActionPerformed
        // TODO add your handling code here:
        JPanel selectedPanel = new AdminHomeJPanel(mainWorkArea);
        mainWorkArea.add("WorkAreaJPanel", selectedPanel);
        CardLayout layout = (CardLayout) mainWorkArea.getLayout();
        layout.next(mainWorkArea);
    }//GEN-LAST:event_btn_HomeActionPerformed

    private void cmb_SortTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_SortTypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmb_SortTypeActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Home;
    private javax.swing.JButton btn_SearchTeam;
    private javax.swing.JComboBox<String> cmb_SearchType;
    private javax.swing.JComboBox<String> cmb_SortType;
    private javax.swing.JLabel lbl_TeamSearchTitle;
    private javax.swing.JTextField txt_SearchField;
    // End of variables declaration//GEN-END:variables
}
