/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.neu.csye6200.peoplemanagementsystem.frames;

import edu.neu.csye6200.peoplemanagementsystem.pojo.TeamObject;
import edu.neu.csye6200.peoplemanagementsystem.services.SearchService;

import java.awt.CardLayout;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Nata
 */
public class TeamListJPanel extends JPanel {

    /**
     * Creates new form TeamListJPanel
     */
    
    JPanel mainWorkArea;
    
        public TeamListJPanel(JPanel mainWorkArea) {
        initComponents();
        this.mainWorkArea = mainWorkArea;
        
        SearchService allemp = new SearchService();
        List<TeamObject> all = new ArrayList<>();
        all = allemp.getAllTeams();
        
        populateTable(all);
        tbl_TeamList.setEnabled(false);
        jScrollPane1.setHorizontalScrollBarPolicy(JScrollPane.HORIZONTAL_SCROLLBAR_ALWAYS);
        tbl_TeamList.setAutoResizeMode(0);
    }
    
     public TeamListJPanel(JPanel mainWorkArea, List<TeamObject> tlist) {
        initComponents();
        this.mainWorkArea = mainWorkArea;  
        populateTable(tlist);
        tbl_TeamList.setEnabled(false);
    }
    
    public void populateTable(List<TeamObject> tList){
        String columns [] = {"Team Organization", "Team Name", "Manager Id", "Team Size", "Team Type"};
        DefaultTableModel dtm = new DefaultTableModel(columns,0);
        for(TeamObject t: tList){
            String team_organization = t.getTeamOrganization();
            String team_name = t.getTeamName();
            Integer managerId = t.getManagerId();
            Integer team_size = t.getTeamId();
            String team_type = t.getTeamType();
            Object [] data = {team_organization, team_name, managerId, team_size, team_type};
            
            dtm.addRow(data);
            
        }
        tbl_TeamList.setModel(dtm);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_TeamListTitle = new javax.swing.JLabel();
        jScrollPane1 = new JScrollPane();
        tbl_TeamList = new javax.swing.JTable();
        btn_Home = new javax.swing.JButton();

        lbl_TeamListTitle.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        lbl_TeamListTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_TeamListTitle.setText("Team List");

        tbl_TeamList.setModel(new DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tbl_TeamList);

        btn_Home.setText("Home");
        btn_Home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_HomeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(188, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(116, 116, 116)
                .addComponent(lbl_TeamListTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_Home)
                .addGap(48, 48, 48))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_TeamListTitle)
                    .addComponent(btn_Home))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(123, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btn_HomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_HomeActionPerformed
        // TODO add your handling code here:
        JPanel selectedPanel = new AdminHomeJPanel(mainWorkArea);
        mainWorkArea.add("WorkAreaJPanel", selectedPanel);
        CardLayout layout = (CardLayout) mainWorkArea.getLayout();
        layout.next(mainWorkArea);
    }//GEN-LAST:event_btn_HomeActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Home;
    private JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_TeamListTitle;
    private javax.swing.JTable tbl_TeamList;
    // End of variables declaration//GEN-END:variables
}
